draw_bold_text_with_bright_colors: true

env:
  TERM: alacritty
  WINT_X11_SCALE_FACTOR: '1.0'

import:
  - ~/.config/alacritty/themes/current.yml

live_config_reload: true

scrolling:
  history: 10000
  multiplier: 3

selection:
  save_to_clipboard: true

# window
window:
  class:
    general: Alacritty
    instance: Alacritty
  opacity: 0.850
  padding:
    x: 0
    y: 0

# font
font:
  normal:
    family: "JetBrainsMono Nerd Font Mono"
    style:  Medium
  bold:
    family: "JetBrainsMono Nerd Font Mono"
    style:  Bold
  italic:
    family: "JetBrainsMono Nerd Font Mono"
    style:  MediumItalic
  bold_italic:
    family: "JetBrainsMono Nerd Font Mono"
    style: BoldItalic
  size: 11.00

# mouse cursor
mousetrue:
  hide_when_typing: true
  url:
    modifiers: Command

# mouse bindings
mouse_bindings:
  - { mouse: Middle, action: PasteSelection }
  - { mouse: Right,  action: Paste }

# key bindings
key_bindings:
  - { key: C, mods: Control|Shift, action: Copy }
  - { key: V, mods: Control|Shift, action: Paste }
  - { key: V, mods: Control,       action: Paste }
