draw_bold_text_with_bright_colors: true

env:
  TERM: alacritty
  WINT_X11_SCALE_FACTOR: '1.0'

import:
  - ~/.config/alacritty/themes/catppuccin-mocha.yml

live_config_reload: true

scrolling:
  history: 10000
  multiplier: 3

selection:
  save_to_clipboard: true

# window
window:
  class:
    general: Alacritty
    instance: Alacritty
  opacity: 0.850
  padding:
    x: 0
    y: 0

# font
font:
  normal:
    family: "JetBrainsMonoNL NFM"
    style:  Medium
  bold:
    family: "JetBrainsMonoNL NFM"
    style:  Bold
  italic:
    family: "JetBrainsMonoNL NFM"
    style:  MediumItalic
  bold_italic:
    family: "JetBrainsMonoNL NFM"
    style: BoldItalic
  size: 11.00
