# live reload
live_config_reload = true

# imports
import = ["~/.config/alacritty/themes/current.toml"]

# settings
[colors]
draw_bold_text_with_bright_colors = true

[scrolling]
history = 10000
multiplier = 3

# env
[env]
TERM = "alacritty"
WINT_X11_SCALE_FACTOR = "1.0"

# cursor
[cursor]
  blink_interval = 5
  style = 'Beam'
  thickness = 0.2
  unfocused_hollow = true

# fonts
[font]
size = 11.0

[font.glyph_offset]
x = 0
y = 0

[font.offset]
x = 0
y = 0

[font.bold]
family = "{{ .FontFamily }}"
style = "Bold"

[font.bold_italic]
family = "{{ .FontFamily }}"
style = "BoldItalic"

[font.italic]
family = "{{ .FontFamily }}"
style = "MediumItalic"

[font.normal]
family = "{{ .FontFamily }}"
style = "Medium"

# mouse curser
[selection]
save_to_clipboard = true

# window
[window]
opacity = 0.85

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 15
y = 0

# mouse bindings
[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

[[mouse.bindings]]
action = "Paste"
mouse = "Right"

# key bindings
[keyboard]
bindings = [
  { mods = "Control|Shift", key = "C", action = "Copy" },
  { mods = "Control|Shift", key = "V", action = "Paste" },
  { mods = "Control", key = "V", action = "Paste" },
]
