font:
  normal:
    family: "JetBrainsMono NFM"
    style:  Medium
  bold:
    family: "JetBrainsMono NFM"
    style:  Bold
  italic:
    family: "JetBrainsMono NFM"
    style:  MediumItalic
  bold_italic:
    family: "JetBrainsMono NFM"
    style: BoldItalic
  size: 10.00
