---
# check if version is the current one / delete if not matching
- name: kubectl > check version
  command: "kubectl version --client=true"
  register: kubectl_version_output
  ignore_errors: true

# download
- name: kubectl > download
  environment: "{{ proxy_env }}"
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/v{{ version.kubectl }}/bin/linux/amd64/kubectl"
    dest: "{{ ansible_env.HOME }}/.local/bin/kubectl"
    mode: u+x
  when: "version.kubectl not in kubectl_version_output.stdout | default('')"
