---
# install
- name: kitty > arch
  include_tasks: arch.yaml
  when: is_wsl == False and ansible_distribution == 'Archlinux'
- name: kitty > debian / ubuntu
  include_tasks: debian.yaml
  when: is_wsl == False and (ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu')
