---
# install
- name: python > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: python > debian / ubuntu
  include_tasks: debian.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
