---
- name: Windows Setup
  hosts: all
  gather_facts: no

  # tags
  tags:
    - default

  # roles
  roles:
    # windows
    - role: win_base
    - role: win_fonts
    - role: win_telemetry
    #- role: win_customization
    - role: win_debloat
    #- role: win_debloatsoftware
    # wsl
    - role: wsl
      when: hostvars[inventory_hostname].feature_wsl | default(false)
    # launcher
    - role: flowlauncher
      when: hostvars[inventory_hostname].app_flowlauncher | default(false)
    # proton
    - role: proton
    # security
    - role: keypassxc
      when: hostvars[inventory_hostname].app_keepassxc | default(false)
    - role: veracrypt
      when: hostvars[inventory_hostname].app_veracrypt | default(false)
    # browser
    - role: firefox
      when: hostvars[inventory_hostname].app_firefox | default(false)
    # development
    - role: vscode
      when: hostvars[inventory_hostname].app_vscode | default(false)
    - role: vscodium
      when: hostvars[inventory_hostname].app_vscodium | default(false)
    - role: jetbrains
    # media
    - role: media
    # misc
    - role: hwmonitor
      when: hostvars[inventory_hostname].app_hwmonitor | default(false)
    # games
    - role: games

  # variables
  vars:
    user: "{{ lookup('env','USER') }}"
    proxy_env:
      http_proxy: "{{ lookup('env','http_proxy') }}"
      https_proxy: "{{ lookup('env','https_proxy') }}"
      no_proxy: "{{ lookup('env','no_proxy') }}"
