---
# check
- name: starship > check version
  command: "starship --version"
  register: starship_version_output
  ignore_errors: true

# download
- name: starship > download
  environment: "{{ proxy_env }}"
  get_url:
    url: "https://github.com/starship/starship/releases/download/v{{ version.starship }}/starship-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/starship-{{ version.starship }}-linux64.tar.gz"
  when: "version.starship not in starship_version_output.stdout | default('')"

# install
- name: starship > install
  ansible.builtin.unarchive:
    src: "/tmp/starship-{{ version.starship }}-linux64.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: yes
  when: "version.starship not in starship_version_output.stdout | default('')"
