# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [
    "nvme"           # NVMe SSDs
    "xhci_pci"       # USB 3.0
    "rtsx_pci_sdmmc" # SD card reader
    "btusb"          # Bluetooth USB support
  ];
  boot.initrd.kernelModules = [
    "mt7921e"       # MediaTek Wi-Fi driver
    "snd_hda_intel" # Audio
  ];
  boot.kernelModules = [
    "kvm-amd" # AMD virtualization
  ];
  boot.extraModulePackages = [ ];
  hardware.firmware = [
    "mediatek/mt7921e.bin" # Wi-Fi firmware
  ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/aac63fee-26c4-4a05-94bd-4c1b8f788d3b";
      fsType = "ext4";
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/A638-7A69";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp2s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
