---
# check if version is the current one / delete if not matching
- name: onefetch > check version
  command: "onefetch --version"
  register: onefetch_version_output
  ignore_errors: true

# download
- name: onefetch > download
  environment: "{{ proxy_env }}"
  get_url:
    url: "https://github.com/o2sh/onefetch/releases/download/{{ version.onefetch }}/onefetch-linux.tar.gz"
    dest: "/tmp/onefetch-{{ version.onefetch }}.tar.gz"
  when: "version.onefetch not in onefetch_version_output.stdout | default('')"

# install
- name: onefetch > install
  ansible.builtin.unarchive:
    src: "/tmp/onefetch-{{ version.onefetch }}.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: yes
    extra_opts:
    - --strip-components=1
  when: "version.onefetch not in onefetch_version_output.stdout | default('')"
