---
# check
- name: zoxide > check version
  command: "zoxide --version"
  register: zoxide_version_output
  ignore_errors: true

# download
- name: zoxide > download
  environment: "{{ proxy_env }}"
  get_url:
    url: "https://github.com/ajeetdsouza/zoxide/releases/download/v{{ zoxide_version }}/zoxide-{{ zoxide_version }}-x86_64-unknown-linux-musl.tar.gz"
    dest: "/tmp/z-{{ zoxide_version }}.tar.gz"
  when: "zoxide_version not in zoxide_version_output.stdout | default('')"

# install
- name: zoxide > install
  ansible.builtin.unarchive:
    src: "/tmp/z-{{ zoxide_version }}.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: yes
  when: "zoxide_version not in zoxide_version_output.stdout | default('')"
