---
# 7ZIP
- name: Base -> 7ZIP
  win_package:
    path: "https://www.7-zip.org/a/7z2501-x64.msi"
    product_id: "7-Zip 25.01 (x64 edition)"
    state: present

# Timezone, Locale and Keyboard
- name: Timezone -> Europe/Berlin
  win_shell: |
    tzutil /s "W. Europe Standard Time"
- name: Locale -> German (Date/Time Formats)
  win_shell: |
    Set-ItemProperty -Path "HKCU:\Control Panel\International" -Name "LocaleName" -Value "de-DE"
    Set-ItemProperty -Path "HKCU:\Control Panel\International" -Name "sShortDate" -Value "dd.MM.yyyy"
    Set-ItemProperty -Path "HKCU:\Control Panel\International" -Name "sLongDate" -Value "dddd, d. MMMM yyyy"
    Set-ItemProperty -Path "HKCU:\Control Panel\International" -Name "sTimeFormat" -Value "HH:mm:ss"
- name: Keyboard -> German Layout
  win_shell: |
    # German keyboard layout code: 00000407
    Set-ItemProperty -Path "HKCU:\Keyboard Layout\Preload" -Name "1" -Value "00000407"

# Mouse Acceleration
- name: Mouse -> Toggle Acceleration
  win_shell: |
    Param($Enable)
    $Path = "HKCU:\Control Panel\Mouse"

    if ($Enable -eq $true) {
        Write-Host "Enabling Mouse Acceleration"
        $MouseSpeed = 1
        $MouseThreshold1 = 6
        $MouseThreshold2 = 10
    } else {
        Write-Host "Disabling Mouse Acceleration"
        $MouseSpeed = 0
        $MouseThreshold1 = 0
        $MouseThreshold2 = 0
    }

    Set-ItemProperty -Path $Path -Name MouseSpeed -Value $MouseSpeed
    Set-ItemProperty -Path $Path -Name MouseThreshold1 -Value $MouseThreshold1
    Set-ItemProperty -Path $Path -Name MouseThreshold2 -Value $MouseThreshold2
  vars:
    Enable: false

# Performance
- name: Performance -> Disable Background Apps
  win_shell: |
    Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications" -Name "GlobalUserDisabled" -Value 1 -Type DWord
#- name: Performance -> Disable Visual Effects
#  win_shell: |
#    Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects" -Name "VisualFXSetting" -Value 2 -Type DWord
