---
# ensure user has video group membership
- name: groups > append video
  become: yes
  become_user: root
  user:
    name: '{{ user }}'
    groups: video
    append: yes

# install
- name: install
  become: yes
  become_user: root
  community.general.zypper:
    name: "{{ item }}"
    state: present
  loop:
    - xwayland
    - wl-clipboard
