---
# install
- name: alacritty > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: alacritty > debian or ubuntu
  include_tasks: debian.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: alacritty > openSUSE
  include_tasks: suse.yaml
  when: ansible_distribution == 'openSUSE Tumbleweed'
