---
# UI
- name: UI -> Left-align Windows Taskbar
  win_shell: |
    Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "TaskbarAl" -Value 0 -Type DWord
- name: UI -> Always show file extensions
  win_shell: |
    Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "HideFileExt" -Value 0 -Type DWord
- name: UI -> Show hidden files in Explorer
  win_shell: |
    Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "Hidden" -Value 1 -Type DWord

# Dark-Mode
- name: UI -> Enable Dark Mode for Apps
  win_shell: |
    # 0 = Light, 1 = Dark
    Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" -Name "AppsUseLightTheme" -Value 0 -Type DWord
- name: UI -> Enable Dark Mode for System
  win_shell: |
    # 0 = Dark, 1 = Light
    Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" -Name "SystemUsesLightTheme" -Value 0 -Type DWord

# Power: Sleep Mode
- name: Power -> Disable Sleep
  win_shell: |
    # Disable Sleep (plugged in)
    Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\238C9FA8-0AAD-41ED-83F4-97BE242C8F20" -Name "ACSettingIndex" -Value 0 -Type DWord

    # Disable Sleep (on battery)
    Set-ItemProperty -Path "HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerSettings\238C9FA8-0AAD-41ED-83F4-97BE242C8F20" -Name "DCSettingIndex" -Value 0 -Type DWord
