---
# UI
- name: UI -> Left-align Windows Taskbar
  win_shell: |
    Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "TaskbarAl" -Value 0 -Type DWord
- name: UI -> Always show file extensions
  win_shell: |
    Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "HideFileExt" -Value 0 -Type DWord
- name: UI -> Show hidden files in Explorer
  win_shell: |
    Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced" -Name "Hidden" -Value 1 -Type DWord

# Dark-Mode
- name: UI -> Enable Dark Mode for Apps
  win_shell: |
    # 0 = Light, 1 = Dark
    Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" -Name "AppsUseLightTheme" -Value 0 -Type DWord
- name: UI -> Enable Dark Mode for System
  win_shell: |
    # 0 = Dark, 1 = Light
    Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize" -Name "SystemUsesLightTheme" -Value 0 -Type DWord

# Disable Animations
- name: UI -> Disable window animations
  win_shell: |
    # Disable minimize / maximize animations
    # MinAnimate = 1 → animate windows when minimizing/maximizing
    # MinAnimate = 0 → disable animations (instant open/close)
    Set-ItemProperty -Path "HKCU:\Control Panel\Desktop\WindowMetrics" -Name "MinAnimate" -Value 0

    # VisualFXSetting controls Windows "Performance Options":
    # 0 → Let Windows decide (default)
    # 1 → Adjust for best appearance (enable all effects)
    # 2 → Adjust for best performance (disable all effects/animations)
    # 3 → Custom (user-configured mix of options)
    Set-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Explorer\VisualEffects" -Name "VisualFXSetting" -Value 2 -Type DWord

# Power: Sleep Mode
- name: Power -> Disable Sleep
  win_shell: |
    # GUIDs
    $subSleep   = "238C9FA8-0AAD-41ED-83F4-97BE242C8F20"  # Sleep settings subgroup
    $sleepIdle  = "29F6C1DB-86DA-48C5-9FDB-F2B67B1F44DA"  # Sleep after idle
    $hibernate  = "9D7815A6-7EE4-497E-8888-515A05F02364"  # Hibernate after idle

    $subDisplay = "7516B95F-F776-4464-8C53-06167F40CC99"  # Display settings subgroup
    $dispIdle   = "3C0BC021-C8A8-4E07-A973-6B14CBCB2B7E"  # Turn off display after idle

    $base = "HKLM:\SYSTEM\CurrentControlSet\Control\Power\PowerSettings"

    # Disable sleep (plugged in + battery)
    Set-ItemProperty -Path "$base\$subSleep\$sleepIdle" -Name "ACSettingIndex" -Value 0 -Type DWord
    Set-ItemProperty -Path "$base\$subSleep\$sleepIdle" -Name "DCSettingIndex" -Value 0 -Type DWord

    # Disable hibernate (plugged in + battery)
    Set-ItemProperty -Path "$base\$subSleep\$hibernate" -Name "ACSettingIndex" -Value 0 -Type DWord
    Set-ItemProperty -Path "$base\$subSleep\$hibernate" -Name "DCSettingIndex" -Value 0 -Type DWord

    # Prevent display from turning off (plugged in + battery)
    Set-ItemProperty -Path "$base\$subDisplay\$dispIdle" -Name "ACSettingIndex" -Value 0 -Type DWord
    Set-ItemProperty -Path "$base\$subDisplay\$dispIdle" -Name "DCSettingIndex" -Value 0 -Type DWord

    # Optional: disable hibernate entirely
    powercfg /hibernate off
