---
# bin
- name: home > bin dir
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: 0755

# bash completions
- name: home > bash completions dir
  file:
    path: "{{ ansible_env.HOME }}/.local/share/bash-completion/completions"
    state: directory
    mode: 0755

# wallpaper dir
- name: home > wallpaper > create dir
  file:
    path: "{{ ansible_env.HOME }}/.local/share/wallpapers"
    state: directory
    mode: 0755
