---
# bin
- name: home > bin dir
  file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    mode: 0755

# bash completions
- name: home > bash completions dir
  file:
    path: "{{ ansible_env.HOME }}/.local/share/bash-completion/completions"
    state: directory
    mode: 0755

# unzip
- name: unzip > install
  become: yes
  become_user: root
  apt:
    name: unzip
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: unzip > install
  become: yes
  become_user: root
  pacman:
    name: unzip
    state: present
  when: ansible_distribution == 'Archlinux'

# wallpaper dir
- name: home > wallpaper > create dir
  file:
    path: "{{ ansible_env.HOME }}/.local/share/wallpapers"
    state: directory
    mode: 0755
