---
# reference: https://github.com/Raphire/Win11Debloat/blob/master/Win11Debloat.ps1
- name: Unwanted Software -> Remove Software
  win_shell: |
    $apps = @(
      "Microsoft.OneDrive",
      "Clipchamp.Clipchamp",
      "Microsoft.3DBuilder",
      "Microsoft.549981C3F5F10",
      "Microsoft.BingFinance",
      "Microsoft.BingFoodAndDrink",
      "Microsoft.BingHealthAndFitness",
      "Microsoft.BingNews",
      "Microsoft.BingSports",
      "Microsoft.BingTranslator",
      "Microsoft.BingTravel",
      "Microsoft.BingWeather",
      "Microsoft.Copilot",
      "Microsoft.Getstarted",
      "Microsoft.Messaging",
      "Microsoft.Microsoft3DViewer",
      "Microsoft.MicrosoftJournal",
      "Microsoft.MicrosoftOfficeHub",
      "Microsoft.MicrosoftPowerBIForWindows",
      "Microsoft.MicrosoftSolitaireCollection",
      "Microsoft.MicrosoftStickyNotes",
      "Microsoft.MixedReality.Portal",
      "Microsoft.NetworkSpeedTest",
      "Microsoft.News",
      "Microsoft.Office.OneNote",
      "Microsoft.Office.Sway",
      "Microsoft.OneConnect",
      "Microsoft.Print3D",
      "Microsoft.SkypeApp",
      "Microsoft.Todos",
      "Microsoft.WindowsAlarms",
      "Microsoft.WindowsFeedbackHub",
      "Microsoft.WindowsMaps",
      "Microsoft.WindowsSoundRecorder",
      "Microsoft.XboxApp",
      "Microsoft.ZuneVideo",
      "MicrosoftCorporationII.MicrosoftFamily",
      "MicrosoftCorporationII.QuickAssist",
      "MicrosoftTeams",
      "MSTeams",
      "Microsoft.BingSearch" # Web Search from Microsoft Bing (Integrates into Windows Search)
    )

    # Start uninstall jobs in parallel
    $jobs = @()
    foreach ($app in $apps) {
        $jobs += Start-Job -ScriptBlock {
            param($id)
            winget uninstall --id $id --accept-source-agreements --disable-interactivity
        } -ArgumentList $app
    }

    # Wait for all jobs to finish
    $jobs | ForEach-Object { Receive-Job -Job $_ -Wait; Remove-Job -Job $_ }

- name: Unwanted Software > Disable autostart
  win_shell: |
    Remove-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run" -Name "OneDrive" -ErrorAction SilentlyContinue
    Get-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run" |
      Get-Member -MemberType NoteProperty |
      Where-Object { $_.Name -like "MicrosoftEdgeAutoLaunch_*" } |
      ForEach-Object {
        Remove-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run" -Name $_.Name -ErrorAction SilentlyContinue
      }
  ignore_errors: yes
