---
# install
- name: git-delta > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: git-delta > bin install
  include_tasks: bininstall.yaml
  when: ansible_distribution != 'Archlinux'
