---
# install
- name: neovim > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: neovim > openSUSE
  include_tasks: suse.yaml
  when: ansible_distribution == 'openSUSE Tumbleweed'
- name: neovim > bin install
  include_tasks: bininstall.yaml
  when: ansible_distribution != 'Archlinux' and ansible_distribution != 'openSUSE Tumbleweed'

# config dir
- name: neovim > create config dir
  file:
    path: "{{ ansible_env.HOME }}/.config/nvim"
    state: directory
    mode: 0755
