---
# check
- name: minioclient > check version
  command: "mc --version"
  register: minioclient_version_output
  ignore_errors: true

# install
- name: minioclient > download
  environment: "{{ proxy_env }}"
  ansible.builtin.get_url:
    url: "https://dl.min.io/client/mc/release/linux-amd64/mc.{{ minioclient_version }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/mc"
    mode: u+x
  when: "minioclient_version not in minioclient_version_output.stdout | default('')"
