---
- name: Yubico -> Authenticator > Check
  win_shell: winget list --id Yubico.Authenticator
  register: winget_check
  ignore_errors: yes
- name: Yubico -> Authenticator > Install
  win_shell: |
    winget install -e --id Yubico.Authenticator
  when: winget_check.rc != 0
