---
# install
- name: htop > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: htop > debian or ubuntu
  include_tasks: debian.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: htop > openSUSE
  include_tasks: suse.yaml
  when: ansible_distribution == 'openSUSE Tumbleweed'
