---
# check if version is the current one / delete if not matching
- name: exa > check version
  command: "exa --version"
  register: exa_version_output
  ignore_errors: true

# download
- name: exa > download
  environment: "{{ proxy_env }}"
  get_url:
    url: "https://github.com/ogham/exa/releases/download/v{{ exa_version }}/exa-linux-x86_64-v{{ exa_version }}.zip"
    dest: "/tmp/exa-v{{ exa_version }}.zip"
  when: "exa_version not in exa_version_output.stdout | default('')"

# install
- name: exa > install
  ansible.builtin.command:
    cmd: "unzip -j -o /tmp/exa-v{{ exa_version }}.zip 'bin/exa' -d {{ ansible_env.HOME }}/.local/bin/"
    warn: false
  when: "exa_version not in exa_version_output.stdout | default('')"
