---
# check
- name: fd > check version
  command: "fd --version"
  register: fd_version_output
  ignore_errors: true

# download
- name: fd > download
  environment: "{{ proxy_env }}"
  get_url:
    url: "https://github.com/sharkdp/fd/releases/download/v{{ fd_version }}/fd-v{{ fd_version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/fd-{{ fd_version }}.tar.gz"
  when: "fd_version not in fd_version_output.stdout | default('')"

# install
- name: fd > install
  ansible.builtin.unarchive:
    src: "/tmp/fd-{{ fd_version }}.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: yes
    extra_opts:
    - --strip-components=1
  when: "fd_version not in fd_version_output.stdout | default('')"
