---
# check
- name: nnn > check version
  command: "nnn -V"
  register: nnn_version_output
  ignore_errors: true

# download
- name: nnn > download
  environment: "{{ proxy_env }}"
  get_url:
    url: "https://github.com/jarun/nnn/releases/download/v{{ nnn_version }}/nnn-nerd-static-{{ nnn_version }}.x86_64.tar.gz"
    dest: "/tmp/nnn-{{ nnn_version }}.tar.gz"
  when: "nnn_version not in nnn_version_output.stdout | default('')"

# install
- name: nnn > install
  ansible.builtin.unarchive:
    src: "/tmp/nnn-{{ nnn_version }}.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: yes
  when: "nnn_version not in nnn_version_output.stdout | default('')"

# symlink
- name: nnn > symlink
  ansible.builtin.file:
    src: "{{ ansible_env.HOME }}/.local/bin/nnn-nerd-static"
    dest: "{{ ansible_env.HOME }}/.local/bin/nnn"
    state: link

# create plugins dir
- name: nnn > plugins > dir
  file:
    path: "{{ ansible_env.HOME }}/.config/nnn/plugins"
    state: directory
    mode: 0755

# download plugins
- name: nnn > plugins > download
  environment: "{{ proxy_env }}"
  ansible.builtin.get_url:
    url: "{{ item.url }}"
    dest: "{{ ansible_env.HOME }}/.config/nnn/plugins/{{ item.dest }}"
  loop:
    - { url: "https://raw.githubusercontent.com/jarun/nnn/master/plugins/preview-tui", dest: "preview-tui" }
