---
# check
- name: sops > check version
  command: "sops --version"
  register: sops_version_output
  ignore_errors: true

# download
- name: sops > download
  environment: "{{ proxy_env }}"
  ansible.builtin.get_url:
    url: "https://github.com/getsops/sops/releases/download/v{{ version.sops }}/sops-v{{ version.sops }}.linux.amd64"
    dest: "{{ ansible_env.HOME }}/.local/bin/sops"
    mode: u+x
  when: "version.sops not in sops_version_output.stdout | default('')"
