---
# install
- name: base > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: base > debian or ubuntu
  include_tasks: debian.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: base > openSUSE
  include_tasks: suse.yaml
  when: ansible_distribution == 'openSUSE Tumbleweed'

# check kind of virtualization
- name: facts > virt_type
  become: yes
  become_user: root
  command: virt-what
  register: virt_type
