#!/usr/bin/env bash

# Notes:
# - hooks are cloned into ~/.cache/pre-commit

# run global pre-commit hooks
pre-commit run --config ~/.config/precommit/.pre-commit-config.yaml --hook-stage commit-message
