---
# check if version is the current one / delete if not matching
- name: node > check version
  command: "{{ ansible_env.HOME }}/.local/share/node/bin/node --version"
  register: node_version_output
  ignore_errors: true
- name: node > delete old version
  file:
   path: "{{ ansible_env.HOME }}/.local/share/node"
   state: absent
  when: "version.nodejs not in node_version_output.stdout | default('')"
  ignore_errors: true

# download
- name: node > download
  environment: "{{ proxy_env }}"
  get_url:
    url: "https://nodejs.org/dist/v{{ version.nodejs }}/node-v{{ version.nodejs }}-linux-x64.tar.xz"
    dest: "/tmp/node-v{{ version.nodejs }}-linux-x64.tar.xz"
  when: "version.nodejs not in node_version_output.stdout | default('')"

# create dir
- name: node > create dir
  file:
    path: "{{ ansible_env.HOME }}/.local/share/node"
    state: directory
    mode: 0755

# install
- name: node > install
  ansible.builtin.unarchive:
    src: "/tmp/node-v{{ version.nodejs }}-linux-x64.tar.xz"
    dest: "{{ ansible_env.HOME }}/.local/share/node"
    remote_src: yes
    extra_opts:
    - --strip-components=1
  when: "version.nodejs not in node_version_output.stdout | default('')"
