---
# install
- name: nodejs > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: nodejs > openSUSE
  include_tasks: suse.yaml
  when: ansible_distribution == 'openSUSE Tumbleweed'
- name: nodejs > bin install
  include_tasks: bininstall.yaml
  when: ansible_distribution != 'Archlinux' and ansible_distribution != 'openSUSE Tumbleweed'
