---
# install
- name: k9s > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: k9s > openSUSE
  include_tasks: suse.yaml
  when: ansible_distribution == 'openSUSE Tumbleweed'
- name: k9s > bin install
  include_tasks: bininstall.yaml
  when: ansible_distribution != 'Archlinux' and ansible_distribution != 'openSUSE Tumbleweed'
