---
- name: ripgrep > version
  ansible.builtin.command: "rg --version"
  register: rg_version_output
  ignore_errors: true

- name: ripgrep > install
  become: yes
  become_user: root
  ansible.builtin.apt:
    deb: https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/ripgrep_{{ ripgrep_version }}_amd64.deb
    force: yes
  when: ansible_distribution == 'Ubuntu' and ripgrep_version not in rg_version_output.stdout
