---
- name: KeePassXC > Check
  win_shell: winget list --id KeePassXCTeam.KeePassXC
  register: winget_check
  ignore_errors: yes
- name: KeePassXC > Install
  win_shell: |
    winget install -e --id KeePassXCTeam.KeePassXC --silent --accept-source-agreements --accept-package-agreements
  when: winget_check.rc != 0
- name: KeePassXC > Disable autostart
  win_shell: |
    Remove-ItemProperty -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Run" -Name "KeePassXC" -ErrorAction SilentlyContinue
  ignore_errors: yes
