---
# install
- name: cliphist > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: cliphist > bin install
  include_tasks: bininstall.yaml
  when: ansible_distribution != 'Archlinux'
