---
# check if version is the current one / delete if not matching
- name: bat > check version
  command: "bat --version"
  register: bat_version_output
  ignore_errors: true

# download
- name: bat > download
  environment: "{{ proxy_env }}"
  get_url:
    url: "https://github.com/sharkdp/bat/releases/download/v{{ version.bat }}/bat-v{{ version.bat }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/bat-v{{ version.bat }}-x86_64-unknown-linux-gnu.tar.gz"
  when: "version.bat not in bat_version_output.stdout | default('')"

# install
- name: bat > install
  ansible.builtin.unarchive:
    src: "/tmp/bat-v{{ version.bat }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: yes
    extra_opts:
    - --strip-components=1
    - --exclude=CHANGELOG.md
    - --exclude=LICENSE-MIT
    - --exclude=LICENSE-APACHE
    - --exclude=README.md
    - --exclude=autocomplete/*
  when: "version.bat not in bat_version_output.stdout | default('')"
