# yaml-language-server: $schema=https://raw.githubusercontent.com/cidverse/reposync/main/configschema/v1.json
version: 1
servers:
  - url: https://github.com
    type: github
    auth:
      username: PhilippHeuer
      password-command: pass show personal/github/readonly-token
    mirror:
      dir: ~/source
      default-action: include
      naming-style: slug
      clone-method: ssh
      rules:
        - rule: group == "docker-gameserver"
          action: exclude
        - rule: group == "stachu540"
          action: exclude
        - rule: group == "oasdiff"
          action: exclude
        - rule: group == "PhilippHeuer" && name == "nixos-nixpkgs"
          action: exclude
