repos:
  # renovate: datasource=github-releases depName=pre-commit/pre-commit-hooks
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace # removes trailing whitespace
      - id: check-executables-have-shebangs # checks that non-binary executables have a proper shebang
      - id: check-yaml
      - id: check-json
      - id: check-xml
      - id: check-toml
  # renovate: datasource=github-releases depName=zricethezav/gitleaks
  #- repo: https://github.com/zricethezav/gitleaks
  #  rev: v8.23.1
  #  hooks:
  #    - id: gitleaks
