user:
    phx:
        hashedPassword: ENC[AES256_GCM,data:M07kdgR0w/WvaPByHrO98jcy4AZaaqQ8SG6eAfr7bLJIpulYWgmN3j6ylV3RJb8E8v7E6KkQK11QRDf8M8tm6Sejc3ZMyvdt0uFcbfY3W2WaoxvJHHvzFVb6qo2/QwYaxvRbMP8Fnhw0Ug==,iv:moqUNhldxo8NB5EQ30UuhHrgMa17/cGDll0twu9svzk=,tag:a75cNJZeNtsHU5BQNSAAeg==,type:str]
notify:
    email:
        server: ENC[AES256_GCM,data:nCLsjBLiB0qVKA4=,iv:tM3S7sCCRJ77oi68bVZByfpQhM+4SQqQOxF8zZq3/0s=,tag:qKYO+MaA0zTu0zyYgu2FZQ==,type:str]
        username: ENC[AES256_GCM,data:74xftk49QTiRX3VhTQ2HDFbkYw==,iv:KVIAVfUV+Mo9yTccx0dRixejjN7b0rk7sDM8qcfnwGM=,tag:4trUfuQ7nXa+E07cS3CkQA==,type:str]
        password: ENC[AES256_GCM,data:gi5oVqqeZSbkOYBD3Br6zR8pSqjvfxnWeb7JMphn,iv:Eng+ZxGsYBt6070XrsfHUCKlNboc0rTmZx+cPY2xVcY=,tag:t20mXzNYll9/3GALwXK3Zg==,type:str]
        to: ENC[AES256_GCM,data:OU1mwK5IJSOyr8QjwEseYryvjJxIVKpirq8OFE0=,iv:cWWg2PkIUyGeLo9UJ+DoR6bvXMgG5E8FGcrQDPLPgbo=,tag:KnPDhdYGJOvh4xxJ+4WnBg==,type:str]
netalert:
    subnet: ENC[AES256_GCM,data:Xm33rwj+YMsrirM4xH5Ioqmjx6bmflaOyH/HZuI+8Q==,iv:PYKHItCvmuKZ1QkQC/ASkrmUkqr2T8lpO2lu6aJIXNg=,tag:5B7D2binJ2xaJvXhb0O61A==,type:str]
    password: ENC[AES256_GCM,data:9P6HfYN+IqA=,iv:/oSCaK9NOdecWGjQSmzevtN31DEIPGFGZqDbHlrmG64=,tag:XOYEsdYFCxJnleebm2s7xg==,type:str]
    email:
        to: ENC[AES256_GCM,data:9BmqguJWp1f803JU8/bLPykAluJvK0S8e11Z2oU8TQ==,iv:y4zpJYO4mfFCdli3eYh/DrQKdZ/w79NJjnbWhjR1QxE=,tag:fmKxJXSNLEBgESHjmYxZKw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hgjjawusp6al8kjgyt9r85zss3kw6dlws8e9ylw859z2a8umg2qkm5nx0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTT3MzVnJHcVF1MjQrT2s1
            bk9kMzJ4R1M3NlAzTDR6bFd6Tkl5QXg2SmpZCk5vbXZHUDFMNDA5K0FGYUFlNUdu
            SDI2SkNwejJadzV4SGVLUlJFY3RJbGMKLS0tIGllS3pFL0NIeW05eUo4OGdMckhC
            dm9zaG1PNHF6eWh3UkRheXNJRXU1RTQKi80O+126+6Qbh2r3OENWW0VrJXBw/doo
            /1qG4w/toT2GNocyGZXrTSV1mFB43/Ty2q1kTLiVFuayjxy9vcgohQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-27T23:42:06Z"
    mac: ENC[AES256_GCM,data:NHyNWhg1EQSpkiwO3emkx5z/Z8Z3r+L09cEynhdbJesmCkOMY435fLg03Pu+C9+vKQlJt62sc62aE9cknfVjPcJTzfxN6X0VvkLam6hBluy1KZTmi7d6KZlr5As1hFF7JwfRmlSCYtAKhHBoztmZudhW3IiDakyQIHYvTlIlEMQ=,iv:NFnOHnn+r4J+Yjo2KaCT5L0ALqEl0UcH88t2RHOEhrw=,tag:p9xzjMQIgUwlI7ypUhuZyg==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.9.2
