user:
    phx:
        hashedPassword: ENC[AES256_GCM,data:M07kdgR0w/WvaPByHrO98jcy4AZaaqQ8SG6eAfr7bLJIpulYWgmN3j6ylV3RJb8E8v7E6KkQK11QRDf8M8tm6Sejc3ZMyvdt0uFcbfY3W2WaoxvJHHvzFVb6qo2/QwYaxvRbMP8Fnhw0Ug==,iv:moqUNhldxo8NB5EQ30UuhHrgMa17/cGDll0twu9svzk=,tag:a75cNJZeNtsHU5BQNSAAeg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hgjjawusp6al8kjgyt9r85zss3kw6dlws8e9ylw859z2a8umg2qkm5nx0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTT3MzVnJHcVF1MjQrT2s1
            bk9kMzJ4R1M3NlAzTDR6bFd6Tkl5QXg2SmpZCk5vbXZHUDFMNDA5K0FGYUFlNUdu
            SDI2SkNwejJadzV4SGVLUlJFY3RJbGMKLS0tIGllS3pFL0NIeW05eUo4OGdMckhC
            dm9zaG1PNHF6eWh3UkRheXNJRXU1RTQKi80O+126+6Qbh2r3OENWW0VrJXBw/doo
            /1qG4w/toT2GNocyGZXrTSV1mFB43/Ty2q1kTLiVFuayjxy9vcgohQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-08-15T23:11:07Z"
    mac: ENC[AES256_GCM,data:M6SROVVHTF4QM7U8QoyIA3mQLCG6vqP6wZ/1HIqJx5DTSGjQEcbJsn3crB/K23Mhcyl7ip0N4jW1ZLnOH4yfg3rzXr/P/CMnPeyyoRXMeQbJU+gcRGNeMqiH70GQXGhFotxDGiMQ7WYFeXdSDDhTwGGlKQbt8m9noeHmYqHYxtM=,iv:xGjYyAQa5cFykcV+UjbZhCEg21Jn+9j1TDEVaKSE1rQ=,tag:F8cukQp3DmfKqvlIwOYrtw==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
