user:
    phx:
        password: ENC[AES256_GCM,data:vhiyvdxC9CUPpf6mhxdcaElQKv+XRKaIXsmPbmAlJG0Zptp+9VxeJWDF0zP/3+b45W55KnfN7Fxb8eA+xCNM9mK5ZrwMFj0XTlCj7SQWLr+3Q5QKmXo39xqRIEoY522q9wa6xnYgf4QQqg==,iv:1P3Ok/4r0AZl2tmz7PzL/5/3PBi5qgkH729GqlZZeCw=,tag:Rna4VAPPj/fiCypfogfNyA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age18hgjjawusp6al8kjgyt9r85zss3kw6dlws8e9ylw859z2a8umg2qkm5nx0
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTT3MzVnJHcVF1MjQrT2s1
            bk9kMzJ4R1M3NlAzTDR6bFd6Tkl5QXg2SmpZCk5vbXZHUDFMNDA5K0FGYUFlNUdu
            SDI2SkNwejJadzV4SGVLUlJFY3RJbGMKLS0tIGllS3pFL0NIeW05eUo4OGdMckhC
            dm9zaG1PNHF6eWh3UkRheXNJRXU1RTQKi80O+126+6Qbh2r3OENWW0VrJXBw/doo
            /1qG4w/toT2GNocyGZXrTSV1mFB43/Ty2q1kTLiVFuayjxy9vcgohQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2023-12-30T17:22:27Z"
    mac: ENC[AES256_GCM,data:8Tgv9b7a/M6qDfXxnZfHw/GGH90zHIt1b6trnz2YSa0SJpFEsOXmHTP5C5ciDKtweqylcTnXRngkOR0mnXulBBZmyIhJhrwCd8WREtL1SkTATIL+HxdhyTEJ60pOxvazZpqWh7U4qOG89G3Riz1zYSGxE1Rllotc3xDo/xpGefQ=,iv:vAwGFatXEFML1ph7tqjpOksQ67sAH6vvYLeJpNSxYmI=,tag:XGeF7TT7y69kO+oi+Kka2g==,type:str]
    pgp: []
    unencrypted_suffix: _unencrypted
    version: 3.8.1
