---
# install
- name: firefox > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: firefox > debian
  include_tasks: debian.yaml
  when: ansible_distribution == 'Debian'
- name: firefox > ubuntu
  include_tasks: ubuntu.yaml
  when: ansible_distribution == 'Ubuntu'
- name: firefox > openSUSE
  include_tasks: suse.yaml
  when: ansible_distribution == 'openSUSE Tumbleweed'

# set as default browser
- name: firefox > set as default browser
  ansible.builtin.shell: |
    xdg-settings set default-web-browser firefox.desktop
