---
# git
- name: git > install
  become: yes
  become_user: root
  apt:
    name: git
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: git > install
  become: yes
  become_user: root
  pacman:
    name: git
    state: present
  when: ansible_distribution == 'Archlinux'

# proxy
- name: git > http proxy
  community.general.git_config:
    name: http.proxy
    value: "{{ proxy_env.http_proxy }}"
    scope: global
  when: proxy_env.http_proxy is defined and proxy_env.http_proxy is not none
- name: git > https proxy
  community.general.git_config:
    name: https.proxy
    value: "{{ proxy_env.https_proxy }}"
    scope: global
  when: proxy_env.https_proxy is defined and proxy_env.https_proxy is not none
