---
# install
- name: git > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: git > debian / ubuntu
  include_tasks: debian.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: git > openSUSE
  include_tasks: suse.yaml
  when: ansible_distribution == 'openSUSE Tumbleweed'

# proxy
- name: git > http proxy
  community.general.git_config:
    name: http.proxy
    value: "{{ proxy_env.http_proxy }}"
    scope: global
  when: proxy_env.http_proxy is defined and proxy_env.http_proxy is not none
- name: git > https proxy
  community.general.git_config:
    name: https.proxy
    value: "{{ proxy_env.https_proxy }}"
    scope: global
  when: proxy_env.https_proxy is defined and proxy_env.https_proxy is not none
