---
- name: binfmt > qemu-user-static
  become: yes
  become_user: root
  pacman:
    name: qemu-user-static
    state: present
- name: binfmt > config
  become: yes
  copy:
    src: qemu-static.conf
    dest: /etc/binfmt.d/qemu-static.conf
