---
# install
- name: binfmt > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: binfmt > debian or ubuntu
  include_tasks: debian.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: binfmt > openSUSE
  include_tasks: suse.yaml
  when: ansible_distribution == 'openSUSE Tumbleweed'

# service
- name: binfmt > systemd-binfmt.service
  become: yes
  ansible.builtin.systemd:
    name: systemd-binfmt.service
    enabled: true
    state: started
