---
# ensure user has video group membership
- name: groups > append video
  user:
    name: '{{ user }}'
    groups: video
    append: yes

# install
- name: install
  become: yes
  become_user: root
  pacman:
    name: "{{ item }}"
    state: present
  loop:
    - xorg-server
    - xorg-xinit
    - xf86-video-vesa
