---
# check
- name: minio-client > check version
  command: "mc --version"
  register: minioclient_version_output
  ignore_errors: true

# install
- name: minio-client > download
  environment: "{{ proxy_env }}"
  ansible.builtin.get_url:
    url: "https://dl.min.io/client/mc/release/linux-amd64/mc.{{ version.minioclient }}"
    dest: "{{ ansible_env.HOME }}/.local/bin/mc"
    mode: u+x
  when: "version.minioclient not in minioclient_version_output.stdout | default('')"
