---
# install
- name: minio-client > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: minio-client > bin install
  include_tasks: bininstall.yaml
  when: ansible_distribution != 'Archlinux'
