---
# sshfs
- name: sshfs > install
  become: yes
  become_user: root
  apt:
    name: sshfs
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: sshfs > install
  become: yes
  become_user: root
  pacman:
    name: sshfs
    state: present
  when: ansible_distribution == 'Archlinux'
- name: sshfs > install
  become: yes
  become_user: root
  community.general.zypper:
    name: sshfs
    state: present
  when: ansible_distribution == 'openSUSE Tumbleweed'
