---
# install
- name: tmux > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: tmux > debian or ubuntu
  include_tasks: debian.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: tmux > openSUSE
  include_tasks: suse.yaml
  when: ansible_distribution == 'openSUSE Tumbleweed'

# service
- name: tmux > service > create
  become: yes
  become_user: root
  copy:
    src: tmux.service
    dest: /etc/systemd/system/tmux.service
  when: is_wsl == True

# enable and start service
- name: tmux > service > enable
  become: yes
  become_user: root
  ansible.builtin.systemd:
    daemon_reload: true
    name: tmux.service
    enabled: true
    state: started
  when: is_wsl == True
