---
# install
- name: tmux > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: tmux > debian or ubuntu
  include_tasks: debian.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: tmux > openSUSE
  include_tasks: suse.yaml
  when: ansible_distribution == 'openSUSE Tumbleweed'

# ssh agent service
- name: tmux > tmux service > create
  copy:
    src: tmux-server.service
    dest: "{{ ansible_env.HOME }}/.config/systemd/user/tmux-server.service"

# enable and start service
- name: tmux > tmux service > enable and start
  ansible.builtin.systemd:
    daemon_reload: yes
    scope: user
    name: tmux-server.service
    enabled: yes
    state: started
  ignore_errors: true
