---
# install
- name: tmux > install
  become: yes
  become_user: root
  apt:
    name: tmux
    state: present
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
- name: tmux > install
  become: yes
  become_user: root
  pacman:
    name: tmux
    state: present
  when: ansible_distribution == 'Archlinux'

# service
- name: tmux > service > create
  become: yes
  become_user: root
  copy:
    src: tmux.service
    dest: /etc/systemd/system/tmux.service
  when: is_wsl == True

# enable and start service
- name: tmux > service > enable
  become: yes
  become_user: root
  ansible.builtin.systemd:
    daemon_reload: true
    name: tmux.service
    enabled: true
    state: started
  when: is_wsl == True
