---
# check
- name: sd > check version
  command: "sd --version"
  register: sd_version_output
  ignore_errors: true

# download
- name: sd > download
  environment: "{{ proxy_env }}"
  ansible.builtin.get_url:
    url: "https://github.com/chmln/sd/releases/download/v{{ sd_version }}/sd-v{{ sd_version }}-x86_64-unknown-linux-gnu"
    dest: "{{ ansible_env.HOME }}/.local/bin/sd"
    mode: u+x
  when: "sd_version not in sd_version_output.stdout | default('')"
