---
# check version
- name: gh > check version
  command: "gh --version"
  register: gh_version_output
  ignore_errors: true

# download
- name: gh > download
  environment: "{{ proxy_env }}"
  get_url:
    url: "https://github.com/cli/cli/releases/download/v{{ gh_version }}/gh_{{ gh_version }}_linux_amd64.tar.gz"
    dest: "/tmp/gh-v{{ gh_version }}-linux-amd64.tar.gz"
  when: "gh_version not in gh_version_output.stdout | default('')"

# install
- name: gh > install
  ansible.builtin.unarchive:
    src: "/tmp/gh-v{{ gh_version }}-linux-amd64.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local"
    remote_src: yes
    extra_opts:
    - --strip-components=1
    - --exclude=LICENSE
  when: "gh_version not in gh_version_output.stdout | default('')"

# check extensions
- name: gh > check extensions
  command: "gh extension list"
  register: gh_extensions_output
  ignore_errors: true

# install extensions
- name: gh > extensions > install
  ansible.builtin.command: "gh extension install {{ item }}"
  loop:
    - "github/gh-copilot"
  when: "item not in gh_extensions_output.stdout | default('')"
  ignore_errors: true

# upgrade extensions
- name: gh > extensions > update
  ansible.builtin.command: "gh extension upgrade {{ item }}"
  loop:
    - "github/gh-copilot"
  ignore_errors: true
