---
# base packages
- name: base packages > install
  become: yes
  become_user: root
  apt:
    name: "{{ item }}"
    state: present
  loop:
  - nala # modern wrapper for the apt
  - unzip # unzip
  - libfido2-dev # fido2 usb driver
