---
# install
- name: base > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: base > debian or ubuntu
  include_tasks: debian.yaml
  when: ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu'
