---
- hosts: all
  # roles
  roles:
    # ansible extensions
    - role: ansible
    # tmux terminal multiplexer
    - role: tmux
    # terminal
    - role: nushell
      vars:
        # renovate: datasource=github-releases depName=nushell/nushell
        nushell_version: "0.85.0"
    - role: starship
      vars:
        # renovate: datasource=github-releases depName=starship/starship
        starship_version: "1.16.0"
    - role: carapace
      vars:
        # renovate: datasource=github-releases depName=rsteube/carapace-bin
        carapace_version: "0.28.0"
    # neovim text editor
    - role: neovim
      vars:
        # renovate: datasource=github-releases depName=neovim/neovim
        nvim_version: "0.9.4"
    # cli tools
    - role: ripgrep
      vars:
        # renovate: datasource=github-releases depName=BurntSushi/ripgrep
        ripgrep_version: "13.0.0"
    - role: fuzzmux
      vars:
        # renovate: datasource=github-releases depName=PhilippHeuer/fuzzmux
        fuzzmux_version: "0.2.1"
    - role: bat
      vars:
        # renovate: datasource=github-releases depName=sharkdp/bat
        bat_version: "0.24.0"
    - role: kubectl
      vars:
        # renovate: datasource=github-releases depName=kubernetes/kubernetes
        kubectl_version: "1.28.2"
    - role: k9s
      vars:
        # renovate: datasource=github-releases depName=derailed/k9s
        k9s_version: "0.27.4"
    # toolchains
    - role: nodejs
      vars:
        # renovate: datasource=github-releases depName=nodejs/node
        nodejs_version: "21.0.0"

  # variables
  vars:
    user: "{{ lookup('env','USER') }}"
    # proxy support
    proxy_env:
      http_proxy: "{{ lookup('env','http_proxy') }}"
      https_proxy: "{{ lookup('env','https_proxy') }}"
      no_proxy: "{{ lookup('env','no_proxy') }}"
