---
- hosts: all
  # roles
  roles:
    - role: facts
    - role: home
    - role: ansible
    - role: binfmt
    # ssh
    - role: ssh
    # core tools
    - role: bat
      tags: [core]
    - role: fzf
      tags: [core]
    - role: sd
      tags: [core]
    - role: fd
      tags: [core]
    - role: htop
      tags: [core]
    - role: btop
      tags: [core]
    - role: fastfetch
      tags: [core]
    - role: eza
      tags: [core]
    - role: zoxide
    # terminal
    - role: tmux
    - role: zellij
    - role: nushell
    - role: starship
    # editor
    - role: neovim
    - role: fuzzmux
    # language toolchains
    - role: java
    - role: nodejs
    - role: python
    # development tools
    - role: git
      tags: [dev]
    - role: gitdelta
      tags: [dev]
    - role: kondo
      tags: [dev]
    - role: reposync
      tags: [dev]
    - role: gh
      tags: [dev]
    - role: lazygit
      tags: [dev]
    - role: precommit
      tags: [dev]
    - role: ripgrep
      tags: [dev]
    # ops
    - role: kubectl
      tags: [ops]
    - role: k9s
      tags: [ops]
    - role: helm
      tags: [ops]
    - role: minioclient
      tags: [ops]
    - role: click
      tags: [ops]
    - role: s3fs
      tags: [ops]
    # gui apps
    - role: kitty
      tags: [desktop]
    # wsl
    - role: wsl

  # variables
  vars:
    # user
    user: "{{ lookup('env','USER') }}"
    # proxy support
    proxy_env:
      http_proxy: "{{ lookup('env','http_proxy') }}"
      https_proxy: "{{ lookup('env','https_proxy') }}"
      no_proxy: "{{ lookup('env','no_proxy') }}"
    # paths
    paths:
      bin: "{{ ansible_env.HOME }}/.local/bin"
      share: "{{ ansible_env.HOME }}/.local/share"
      licenses: "{{ ansible_env.HOME }}/.local/share/licenses"
      completions_bash: "{{ ansible_env.HOME }}/.local/share/bash-completion/completions"
    # versions
    version:
      # renovate: datasource=github-releases depName=sharkdp/bat
      bat: "0.24.0"
      # renovate: datasource=github-releases depName=junegunn/fzf
      fzf: "0.44.1"
      # renovate: datasource=github-releases depName=chmln/sd
      sd: "1.0.0"
      # renovate: datasource=github-releases depName=sharkdp/fd
      fd: "8.7.1"
      # renovate: datasource=github-releases depName=aristocratos/btop
      btop: "1.2.13"
      # renovate: datasource=github-releases depName=fastfetch-cli/fastfetch
      fastfetch: "2.2.3"
      # renovate: datasource=github-releases depName=eza-community/eza
      eza: "0.16.1"
      # renovate: datasource=github-releases depName=dandavison/delta
      gitdelta: "0.16.5"
      # renovate: datasource=github-releases depName=zellij-org/zellij
      zellij: "0.39.1"
      # renovate: datasource=github-releases depName=nushell/nushell
      nushell: "0.87.1"
      # renovate: datasource=github-releases depName=starship/starship
      starship: "1.16.0"
      # renovate: datasource=github-releases depName=neovim/neovim
      neovim: "0.9.4"
      # renovate: datasource=github-releases depName=PhilippHeuer/fuzzmux
      fuzzmux: "0.3.1"
      # renovate: datasource=github-releases depName=tbillington/kondo
      kondo: "0.7"
      # renovate: datasource=github-releases depName=ajeetdsouza/zoxide
      zoxide: "0.9.2"
      # renovate: datasource=github-releases depName=cidverse/reposync
      reposync: "0.3.0"
      # renovate: datasource=github-releases depName=nodejs/node
      nodejs: "21.2.0"
      # renovate: datasource=github-releases depName=cli/cli
      gh: "2.39.2"
      # renovate: datasource=github-releases depName=jesseduffield/lazygit
      lazygit: "0.40.2"
      # renovate: datasource=pip depName=pre-commit
      precommit: "3.5.0"
      # renovate: datasource=github-releases depName=BurntSushi/ripgrep
      ripgrep: "14.0.1"
      # renovate: datasource=github-releases depName=kubernetes/kubernetes
      kubectl: "1.28.4"
      # renovate: datasource=github-releases depName=derailed/k9s
      k9s: "0.28.2"
      # renovate: datasource=github-releases depName=helm/helm
      helm: "3.13.2"
      # renovate: datasource=github-releases depName=minio/mc
      minioclient: "RELEASE.2023-11-20T16-30-59Z"
      # renovate: datasource=github-releases depName=databricks/click
      click: "0.6.3"
