---
- hosts: all

  # tags
  tags:
    - base
    - core
    - dev
    - ops
    - desktop

  # roles
  roles:
    - role: facts         # gather facts
    - role: home          # prepare home directory
    - role: vm            # virtualization
    - role: ansible       # ansible configuration
    - role: binfmt        # binfmt support

    # base configuration
    - role: base          # basic distro configuration
    - role: fonts         # fonts
    - role: dotfilescli   # simple cli tool to manage dotfiles

    # ssh
    - role: ssh           # ssh client configuration

    # core tools
    - role: bat           # cat clone with syntax highlighting
      tags: [core]
    - role: fzf           # command-line fuzzy finder
      tags: [core]
    - role: sd            # intuitive alternative to sed
      tags: [core]
    - role: fd            # simple, fast and user-friendly alternative to find
      tags: [core]
    - role: htop          # interactive process viewer
      tags: [core]
    - role: btop          # resource monitor that shows usage and stats for processor, memory, disks, network and processes
      tags: [core]
    - role: fastfetch     # fast system info for linux and bsd
      tags: [core]
    - role: eza           # modern replacement for ls
      tags: [core]
    - role: zoxide        # fast cd command that learns your habits
      tags: [core]

    # terminal
    - role: tmux          # terminal multiplexer
    - role: zellij        # terminal multiplexer (alternative to tmux)
    - role: nushell       # modern shell written in rust
    - role: starship      # cross-shell prompt

    # editor
    - role: neovim        # vim-fork focused on extensibility and usability
    - role: fuzzmux       # fuzzy finder for ssh, projects, k8s, and more to create terminal multiplexer sessions

    # language toolchains
    - role: java
    - role: nodejs
    - role: python
    - role: golang

    # development tools
    - role: git           # distributed version control system
      tags: [dev]
    - role: gitdelta      # syntax-highlighting pager for git and diff output
      tags: [dev]
    - role: kondo         # tool to cleanup build artifacts, caches, ...
      tags: [dev]
    - role: reposync      # syncronize all git repositories from a remote platform
      tags: [dev]
    - role: gh            # github cli
      tags: [dev]
    - role: lazygit       # simple terminal UI for git commands
      tags: [dev]
    - role: precommit     # framework for managing and maintaining multi-language pre-commit hooks
      tags: [dev]
    - role: ripgrep       # grep-like text search for source code
      tags: [dev]
    - role: onefetch      # terminal tool to display git repository summary
      tags: [dev]

    # secret management
    - role: sops          # Secrets OPerationS
      tags: [secrets]
    #- role: vault         # hashicorp vault
    #  tags: [secrets]

    # k8s
    - role: kubectl       # kubernetes cli
      tags: [ops]
    - role: k9s           # terminal UI to interact with your kubernetes clusters
      tags: [ops]
    - role: helm          # package manager for kubernetes
      tags: [ops]
    - role: click         # cli interactive controller for kubernetes
      tags: [ops]

    # s3
    - role: minioclient   # minio client
      tags: [ops]
    - role: s3fs          # fuse-based file system backed by amazon s3
      tags: [ops]

    # desktop
    - role: wayland       # wayland
      tags: [desktop]
    # desktop - terminal emulator
    - role: alacritty     # alacritty
      tags: [desktop]
    # desktop - window manager
    - role: cliphist      # clipboard history
      tags: [desktop]
    - role: waybar        # waybar
      tags: [desktop]
    - role: dunst         # dunst notifications
      tags: [desktop]
    - role: swww          # wayland wallpaper daemon
      tags: [desktop]
    - role: sway          # sway
      tags: [desktop]
    - role: hyprland      # hyprland
      tags: [desktop]
    # desktop - apps
    - role: rofi          # application launcher
      tags: [desktop]
    - role: thunar        # file manager
      tags: [desktop]
    - role: sxiv          # image viewer
      tags: [desktop]
    - role: firefox       # firefox web browser
      tags: [desktop]

    # wsl
    - role: wsl           # windows subsystem for linux configuration
      when: is_wsl == True

  # variables
  vars:
    # user
    user: "{{ lookup('env','USER') }}"
    # proxy support
    proxy_env:
      http_proxy: "{{ lookup('env','http_proxy') }}"
      https_proxy: "{{ lookup('env','https_proxy') }}"
      no_proxy: "{{ lookup('env','no_proxy') }}"
    # paths
    paths:
      bin: "{{ ansible_env.HOME }}/.local/bin"
      share: "{{ ansible_env.HOME }}/.local/share"
      licenses: "{{ ansible_env.HOME }}/.local/share/licenses"
      completions_bash: "{{ ansible_env.HOME }}/.local/share/bash-completion/completions"
    # versions
    version:
      # renovate: datasource=github-releases depName=sharkdp/bat
      bat: "0.24.0"
      # renovate: datasource=github-releases depName=junegunn/fzf
      fzf: "0.45.0"
      # renovate: datasource=github-releases depName=chmln/sd
      sd: "1.0.0"
      # renovate: datasource=github-releases depName=sharkdp/fd
      fd: "9.0.0"
      # renovate: datasource=github-releases depName=aristocratos/btop
      btop: "1.3.0"
      # renovate: datasource=github-releases depName=fastfetch-cli/fastfetch
      fastfetch: "2.5.0"
      # renovate: datasource=github-releases depName=eza-community/eza
      eza: "0.17.1"
      # renovate: datasource=github-releases depName=dandavison/delta
      gitdelta: "0.16.5"
      # renovate: datasource=github-releases depName=zellij-org/zellij
      zellij: "0.39.2"
      # renovate: datasource=github-releases depName=nushell/nushell
      nushell: "0.89.0"
      # renovate: datasource=github-releases depName=starship/starship
      starship: "1.17.1"
      # renovate: datasource=github-releases depName=neovim/neovim
      neovim: "0.9.5"
      # renovate: datasource=github-releases depName=PhilippHeuer/fuzzmux
      fuzzmux: "0.3.1"
      # renovate: datasource=github-releases depName=tbillington/kondo
      kondo: "0.8"
      # renovate: datasource=github-releases depName=ajeetdsouza/zoxide
      zoxide: "0.9.2"
      # renovate: datasource=github-releases depName=cidverse/reposync
      reposync: "0.3.0"
      # renovate: datasource=github-releases depName=nodejs/node
      nodejs: "21.6.0"
      # renovate: datasource=github-releases depName=cli/cli
      gh: "2.42.0"
      # renovate: datasource=github-releases depName=jesseduffield/lazygit
      lazygit: "0.40.2"
      # renovate: datasource=pip depName=pre-commit
      precommit: "3.5.0"
      # renovate: datasource=github-releases depName=BurntSushi/ripgrep
      ripgrep: "14.1.0"
      # renovate: datasource=github-releases depName=kubernetes/kubernetes
      kubectl: "1.29.0"
      # renovate: datasource=github-releases depName=derailed/k9s
      k9s: "0.31.5"
      # renovate: datasource=github-releases depName=helm/helm
      helm: "3.13.3"
      # renovate: datasource=github-releases depName=minio/mc
      minioclient: "RELEASE.2023-11-20T16-30-59Z"
      # renovate: datasource=github-releases depName=databricks/click
      click: "0.6.3"
      # renovate: datasource=github-releases depName=PhilippHeuer/dotfiles-cli
      dotfilescli: "0.2.5"
      # renovate: datasource=github-releases depName=o2sh/onefetch
      onefetch: "2.19.0"
      # renovate: datasource=github-releases depName=Horus645/swww
      swww: "0.8.2"
      # renovate: datasource=github-releases depName=sentriz/cliphist
      cliphist: "0.4.0"
      # renovate: datasource=github-releases depName=getsops/sops
      sops: "3.8.1"
