---
- hosts: all
  # roles
  roles:
    # ansible
    - role: ansible
    # core tools
    - role: coreutils
      vars:
        # renovate: datasource=github-releases depName=sharkdp/bat
        bat_version: "0.24.0"
        # renovate: datasource=github-releases depName=junegunn/fzf
        fzf_version: "0.44.1"
        # renovate: datasource=github-releases depName=chmln/sd
        sd_version: "1.0.0"
        # renovate: datasource=github-releases depName=sharkdp/fd
        fd_version: "8.7.1"
        # renovate: datasource=github-releases depName=aristocratos/btop
        btop_version: "1.2.13"
        # renovate: datasource=github-releases depName=fastfetch-cli/fastfetch
        fastfetch_version: "2.2.3"
        # renovate: datasource=github-releases depName=jarun/nnn
        nnn_version: "4.9"
        # renovate: datasource=github-releases depName=ogham/exa
        exa_version: "0.10.1"
    # dev tools
    - role: git
      vars:
        # renovate: datasource=github-releases depName=dandavison/delta
        gitdelta_version: "0.16.5"
    - role: ssh
    # terminal
    - role: tmux
    - role: zellij
      vars:
        # renovate: datasource=github-releases depName=zellij-org/zellij
        zellij_version: "0.39.1"
    - role: nushell
      vars:
        # renovate: datasource=github-releases depName=nushell/nushell
        nushell_version: "0.87.0"
    - role: starship
      vars:
        # renovate: datasource=github-releases depName=starship/starship
        starship_version: "1.16.0"
    # neovim text editor
    - role: neovim
      vars:
        # renovate: datasource=github-releases depName=neovim/neovim
        nvim_version: "0.9.4"
    # cli tools
    - role: ripgrep
      vars:
        # renovate: datasource=github-releases depName=BurntSushi/ripgrep
        ripgrep_version: "13.0.0"
    - role: fuzzmux
      vars:
        # renovate: datasource=github-releases depName=PhilippHeuer/fuzzmux
        fuzzmux_version: "0.3.1"
    - role: kondo
      vars:
        # renovate: datasource=github-releases depName=tbillington/kondo
        kondo_version: "0.7"
    - role: zoxide
      vars:
        # renovate: datasource=github-releases depName=ajeetdsouza/zoxide
        zoxide_version: "0.9.2"
    - role: reposync
      vars:
        # renovate: datasource=github-releases depName=cidverse/reposync
        reposync_version: "0.3.0"
    # language toolchains
    - role: nodejs
      vars:
        # renovate: datasource=github-releases depName=nodejs/node
        nodejs_version: "21.2.0"
    # development tools
    - role: dev
      vars:
        # renovate: datasource=github-releases depName=cli/cli
        gh_version: "2.39.1"
        # renovate: datasource=github-releases depName=jesseduffield/lazygit
        lazygit_version: "0.40.2"
    # devops tooling
    - role: devops
      vars:
        # renovate: datasource=github-releases depName=kubernetes/kubernetes
        kubectl_version: "1.28.4"
        # renovate: datasource=github-releases depName=derailed/k9s
        k9s_version: "0.28.2"
        # renovate: datasource=github-releases depName=helm/helm
        helm_version: "3.13.2"
        # renovate: datasource=github-releases depName=minio/mc
        minioclient_version: "RELEASE.2023-10-24T21-42-22Z"
        # renovate: datasource=github-releases depName=databricks/click
        click_version: "0.6.3"
    # wsl
    - role: wsl

  # variables
  vars:
    # user
    user: "{{ lookup('env','USER') }}"
    # proxy support
    proxy_env:
      http_proxy: "{{ lookup('env','http_proxy') }}"
      https_proxy: "{{ lookup('env','https_proxy') }}"
      no_proxy: "{{ lookup('env','no_proxy') }}"
    # paths
    paths:
      bin: "{{ ansible_env.HOME }}/.local/bin"
      share: "{{ ansible_env.HOME }}/.local/share"
      licenses: "{{ ansible_env.HOME }}/.local/share/licenses"
      completions_bash: "{{ ansible_env.HOME }}/.local/share/bash-completion/completions"
