---
- hosts: all
  # roles
  roles:
    # ansible
    - role: ansible
    # core tools
    - role: coreutils
      vars:
        # renovate: datasource=github-releases depName=sharkdp/bat
        bat_version: "0.24.0"
        # renovate: datasource=github-releases depName=junegunn/fzf
        fzf_version: "0.43.0"
        # renovate: datasource=github-releases depName=chmln/sd
        sd_version: "0.7.6"
        # renovate: datasource=github-releases depName=sharkdp/fd
        fd_version: "8.7.1"
        # renovate: datasource=github-releases depName=aristocratos/btop
        btop_version: "1.2.13"
        # renovate: datasource=github-releases depName=jarun/nnn
        nnn_version: "4.9"
    # dev tools
    - role: git
      vars:
        # renovate: datasource=github-releases depName=dandavison/delta
        gitdelta_version: "0.16.5"
    - role: ssh
    # terminal
    - role: tmux
    - role: zellij
      vars:
        # renovate: datasource=github-releases depName=zellij-org/zellij
        zellij_version: "0.38.2"
    - role: nushell
      vars:
        # renovate: datasource=github-releases depName=nushell/nushell
        nushell_version: "0.86.0"
    - role: starship
      vars:
        # renovate: datasource=github-releases depName=starship/starship
        starship_version: "1.16.0"
    # neovim text editor
    - role: neovim
      vars:
        # renovate: datasource=github-releases depName=neovim/neovim
        nvim_version: "0.9.4"
    # cli tools
    - role: ripgrep
      vars:
        # renovate: datasource=github-releases depName=BurntSushi/ripgrep
        ripgrep_version: "13.0.0"
    - role: fuzzmux
      vars:
        # renovate: datasource=github-releases depName=PhilippHeuer/fuzzmux
        fuzzmux_version: "0.3.0"
    - role: kondo
      vars:
        # renovate: datasource=github-releases depName=tbillington/kondo
        kondo_version: "0.7"
    - role: zoxide
      vars:
        # renovate: datasource=github-releases depName=ajeetdsouza/zoxide
        zoxide_version: "0.9.2"
    - role: reposync
      vars:
        # renovate: datasource=github-releases depName=cidverse/reposync
        reposync_version: "0.3.0"
    # language toolchains
    - role: nodejs
      vars:
        # renovate: datasource=github-releases depName=nodejs/node
        nodejs_version: "21.1.0"
    # devops tooling
    - role: devops
      vars:
        # renovate: datasource=github-releases depName=kubernetes/kubernetes
        kubectl_version: "1.28.3"
        # renovate: datasource=github-releases depName=derailed/k9s
        k9s_version: "0.27.4"
        # renovate: datasource=github-releases depName=helm/helm
        helm_version: "3.13.1"
        # renovate: datasource=github-releases depName=minio/mc
        minioclient_version: "RELEASE.2023-10-24T21-42-22Z"
    # wsl
    - role: wsl

  # variables
  vars:
    # user
    user: "{{ lookup('env','USER') }}"
    # proxy support
    proxy_env:
      http_proxy: "{{ lookup('env','http_proxy') }}"
      https_proxy: "{{ lookup('env','https_proxy') }}"
      no_proxy: "{{ lookup('env','no_proxy') }}"
