# yaml-language-server: $schema=https://json.schemastore.org/lazygit.json

# Lazygit configuration file
#
# see https://github.com/jesseduffield/lazygit/blob/master/docs/Config.md

# gui
gui:
  showRandomTip: false
  showFileTree: true
  showBranchCommitHash: true # show commit hashes alongside branch names
  showBottomLine: false # for hiding the bottom information line (unless it has important information to tell you)
  showIcons: true # show nerd font icons
  showCommandLog: true
  commandLogSize: 8
  nerdFontsVersion: "3" # nerd fonts version to use ("2" or "3"); empty means don't show nerd font icons
  splitDiff: 'auto' # one of 'auto' | 'always'
  border: 'rounded' # one of 'single' | 'double' | 'rounded' | 'hidden'

  # side panel takes up 1/3 of the screen
  sidePanelWidth: 0.3333

  # play animation when nuking
  animateExplosion: true

# git
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
    useConfig: false

# os settings
os:
  # edit with neovim
  editPreset: "nvim"

  # open links with default browser
  openLink: open {{link}}

# refresh
refresher:
  refreshInterval: 10
  fetchInterval: 60

# disables the popup that shows when you start lazygit
disableStartupPopups: true

# what happens when the dir is not a repository (one of: 'prompt' | 'create' | 'skip' | 'quit')
notARepository: 'skip'

# no idea what this is
promptToReturnFromSubprocess: true
