---
# check
- name: btop > check version
  command: "btop --version"
  register: btop_version_output
  ignore_errors: true

# download
- name: btop > download
  environment: "{{ proxy_env }}"
  get_url:
    url: "https://github.com/aristocratos/btop/releases/download/v{{ version.btop }}/btop-x86_64-linux-musl.tbz"
    dest: "/tmp/btop-{{ version.btop }}.tbz"
  when: "version.btop not in btop_version_output.stdout | default('')"

# install
- name: btop > install
  ansible.builtin.command:
    cmd: "tar -xjf /tmp/btop-{{ version.btop }}.tbz --strip-components 3 -C {{ ansible_env.HOME }}/.local/bin ./btop/bin/btop"
  when: "version.btop not in btop_version_output.stdout | default('')"
