---
# check
- name: fd > check version
  command: "fd --version"
  register: fd_version_output
  ignore_errors: true

# download
- name: fd > download
  environment: "{{ proxy_env }}"
  get_url:
    url: "https://github.com/sharkdp/fd/releases/download/v{{ version.fd }}/fd-v{{ version.fd }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/fd-{{ version.fd }}.tar.gz"
  when: "version.fd not in fd_version_output.stdout | default('')"

# install
- name: fd > install
  ansible.builtin.unarchive:
    src: "/tmp/fd-{{ version.fd }}.tar.gz"
    dest: "{{ ansible_env.HOME }}/.local/bin"
    remote_src: yes
    extra_opts:
    - --strip-components=1
  when: "version.fd not in fd_version_output.stdout | default('')"
