---
# install
- name: nushell > arch
  include_tasks: arch.yaml
  when: ansible_distribution == 'Archlinux'
- name: nushell > openSUSE
  include_tasks: suse.yaml
  when: ansible_distribution == 'openSUSE Tumbleweed'
- name: nushell > bin install
  include_tasks: bininstall.yaml
  when: ansible_distribution != 'Archlinux' and ansible_distribution != 'openSUSE Tumbleweed'

# add to /etc/shells
- name: nushell > add to /etc/shells
  become: yes
  become_user: root
  lineinfile:
    path: /etc/shells
    line: /usr/bin/nu
    state: present
