

---
# check if version is the current one / delete if not matching
- name: node > check version
  command: "nu --version"
  register: nu_version_output
  ignore_errors: true

# download
- name: nushell > download
  get_url:
    url: "https://github.com/nushell/nushell/releases/download/{{ nushell_version }}/nu-{{ nushell_version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: "/tmp/nu-{{ nushell_version }}-x86_64-unknown-linux-gnu.tar.gz"
  when: "nushell_version not in nu_version_output.stdout | default('')"

# install
- name: nushell > install
  become: yes
  become_user: root
  ansible.builtin.unarchive:
    src: "/tmp/nu-{{ nushell_version }}-x86_64-unknown-linux-gnu.tar.gz"
    dest: /usr/bin
    remote_src: yes
    extra_opts:
    - --strip-components=1
    - --exclude=README.md
    - --exclude=LICENSE
    - --exclude=nu_plugin_example
  when: "nushell_version not in nu_version_output.stdout | default('')"

# add to /etc/shells
- name: nushell > add to /etc/shells
  become: yes
  become_user: root
  lineinfile:
    path: /etc/shells
    line: /usr/bin/nu
    state: present
